### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by saroar** [AlexShubin/SwiftPushServer#1]
Thanks for your time :)
is it will work production server?

**Comment by AlexShubin** [comment]
Hi! Yes it should, but I think it needs some updates for swift 4 etc. I didn’t commit into that for a long time, cause I made it just for fun:)
I think I can do it soon… Stay tuned.

**Comment by saroar** [comment]
how i can create AuthKey_XXXXX.p8 this auth key for production my local working but production not :( 
or is it only for push Server @AlexShubin and is it a good idea to create push server separately than my original API server?

**Comment by saroar** [comment]
just fixed `AuthKey_XXXXXXX.p8` now working to my production thanks but I like ur project

**Comment by AlexShubin** [comment]
Thanks, enjoy:)

**Comment by saroar** [comment]
@AlexShubin is it a good idea to create push server separately than original API server?

**Comment by AlexShubin** [comment]
I don't have enough exp-ce in the server side. Separated things should be easier to maintain. Anyway I think if it works for you - then it's good.
