### ISSUE TITLE
PushKit

### ISSUE THREAD

**Issue by saroar** [AlexShubin/SwiftPushServer#2]
is it work with VoIP push notifications?

here I am using this swift package https://github.com/PerfectlySoft/Perfect-Notifications for send push notification for my app its work fine but my question can i use the same package for VoIP push notifications for a voice call when my app is offline

**Comment by AlexShubin** [comment]
Hi Saroar. With the package you’ve mentioned I think you can’t. But may be they have other solutions to solve your problem. They have very nice support and  respond very quickly. Try their’s slack chat http://www.perfect.ly

**Comment by saroar** [comment]
i dont think they have it :( i already try slack thanks for your reply if know other swift package let me know thanks again

**Comment by AlexShubin** [comment]
Yeah, I assumed so. Good luck!
