### ISSUE TITLE
Where I can find an API to that project?

### ISSUE THREAD

**Issue by febick** [AlexShubin/SwiftPushServer#3]
Web-interface work well, but I can find any information about API-keys.

**Comment by AlexShubin** [comment]
Hey! Thanks for your interest! :) I did this project quite a long time ago just for fun, so I didn't document that well. To send push via API request you need to perform post request to `/send_notification`. You can check out this method to figure out what parameters you need to pass: https://github.com/AlexShubin/SwiftPushServer/blob/515de5ec2986fa3faa5029ce428e2fd656b9b632/Sources/UIRoutesProvider.swift#L171
and this file:
https://github.com/AlexShubin/SwiftPushServer/blob/4185507a57c8a0f31eff222ae26113afcfa1111d/Sources/APIRoutesProvider.swift

**Comment by febick** [comment]
Thanks a lot! It's works perfect!
